# 1.numpy的属性介绍

In [ ]:
#导包
import numpy as np

In [ ]:
#1. 创建的numpy的ndarray对象
a = np.array([1, 2, 3])
arr = np.arange(10)
print(arr)
arr1 = np.arange(15).reshape(3, 5)  #排成3行5列

print(arr1)

In [ ]:
#2.演示常用属性
print(f'arr1的轴：{arr1.ndim}')
print(f'numpy的维度是：{arr1.shape}')
print(f'numpy的元素类型是：{arr1.dtype}')
print(f'numpy的元素个数是{arr1.size}')
print(f'numpy的元素类型是：{type(arr1)}')


In [ ]:
# 创建ndarray
#1.array()
a = np.array([1, 2, 4])
#2.arange()
np_arange = np.arange(10, 20, 5)
print(np_arange)
#3. 创建随机数矩阵
arr = np.random.rand(3, 4)  #生成随机3行4列的浮点数据
print(arr)
print(type(arr))
arr = np.random.randint(-1, 5, size=(3, 4))  #生成随机3行4列的整型数据

print(arr)
print(type(arr))

arr = np.random.uniform(-1, 5, size=(3, 4))  #生成3行4列随机的浮点数据。在指定范围里面生成
print(arr)
print(type(arr))



In [ ]:
#类型转换
#array(),把列表转化为ndarray
my_list = [1, 2, 3]
print(type(my_list))
arr2 = np.array(my_list)
print(arr2)
#arange()函数，创建ndarray对象
arr = np.arange(10, 20, 2, dtype=int)
print(type(arr))
print(arr.dtype)





In [ ]:
#numpy的类型转换astype()
arr = np.arange(1, 10, 2, dtype=np.int64)
print(arr.dtype)
arr2 = arr.astype(np.float64)
print(arr2)
print(arr2.dtype)




In [ ]:
#创建等差等比数列
#np.logspace等比数列 开始点和结束点是10的幂
a = np.logspace(0, 2, 10)
print(a)
#还可以改变基数
a = np.logspace(0, 9, 10, base=2)
print(a)
#等差数列 可以使用endpoint决定是否包含终止值，默认值为True
a = np.linspace(0, 2, 10)
print(a)
a = np.linspace(0, 10, 10, endpoint=False)
print(a)


In [ ]:
#numpy内置函数
#1.基本函数
#rand() 返回一个具有标准正态分布的序列 参数为数组形状
a = np.random.rand(2, 3)
print(a)
print(np.ceil(a))  #天花板函数，向上取整
print(np.floor(a))  #地板函数，向下取整
print(np.rint(a))  #四舍五入
print(np.abs(a))
print(np.multiply(a, a))  #行列一致时的矩阵乘法
print(a * a)
print(np.divide(a, a))  #同上，矩阵除法
print(np.where(a > 0, 1, -1))  #类似三元表达式



In [29]:
#2.统计函数
arr1 = np.arange(12).reshape(3, 4)
print(arr1)
print(np.cumsum(arr1))  #累加和，返回一个数组


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [30]:
print(np.sum(arr1))  #求和函数，返回一个数
print(np.sum(arr1, axis=0))  # 0->每列求和，返回一个数组
print(np.sum(arr1, axis=1))  #1->每行求和，返回一个数组


66
[12 15 18 21]
[ 6 22 38]


In [34]:
#去重函数
arr1 = np.array([[1, 2, 1], [2, 3, 5]])
print(arr1)
arr2 = np.unique(arr1)  #去重，返回新副本
print(arr2)

[[1 2 1]
 [2 3 5]]
[1 2 3 5]


In [44]:
#排序函数
arr = np.array([11, 33, 22, 55])
print(np.sort(arr))
print(arr)

[11 22 33 55]
[11 33 22 55]


In [38]:
#通过对象的方法直接修改数组
print(f'排序前：{arr}')
arr.sort()
print(f'排序后：{arr}')

排序前：[11 22 33 55]
排序后：[11 22 33 55]


In [43]:
#基本运算
#1.矩阵的加减
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(c)
#2.矩阵相乘
#对应位置相乘
a = np.array([20, 30, 40, 50])
b = np.array([20, 30, 40, 50])
print(a * b)
#线性代数的矩阵相乘
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)
print(a.dot(b))  #print(np.dot(a,b))
print(b @ a)  #和上面的写法相当



[20 29 38 47]
[ 400  900 1600 2500]
[[10 13]
 [28 40]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
